class Category{

  List<String> getCategories(){
    return [
      'Accounts',
      'Arabic',
      'Art',
      'Artificial Intelligence',
      'Biology',
      'Business Intelligence',
      'Business Studies',
      'Chemisty',
      'Chinese Mandarin',
      'Chinese',
      'Computer Science',
      'Computer Studies',
      'Criminology',
      'Economics',
      'Electrical Engineering',
      'English Literature',
      'English',
      'Entrepreneurship',
      'Environmental Science',
      'French',
      'Geography',
      'German',
      'Graphic Design',
      'Graphical Communication',
      'Health',
      'History',
      'Home Economics',
      'Hospitality',
      'IT',
      'Information Technology',
      'Italian',
      'Learning Disabilities',
      'Maltese',
      'Marketing',
      'Mathematics',
      'Maths',
      'Mechanical Engineering',
      'Philosophy',
      'Physical Education',
      'Physics',
      'Psychology',
      'Pure Maths',
      'Religion',
      'Russian',
      'Social Care',
      'Social Studies',
      'Sociology',
      'Software Development',
      'Spanish',
      'Systems of Knowledge',
    ];
  }
}