class Category{

  List<String> getCategories(){
    return [
      'Accounts',
      'Arabic',
      'Art',
      'Biology',
      'Business Studies',
      'Chemisty',
      'Chinese',
      'Chinese Manderin',
      'Computer Studies',
      'IT',
      'Information Technology',
      'Criminology',
      'Economics',
      'English',
      'English Literature',
      'Environmental Science',
      'French',
      'Geography',
      'German',
      'Graphic Design',
      'Graphical Communication',
      'Health',
      'Social Care',
      'History',
      'Home Economics',
      'Hospitality',
      'Italian',
      'Learning Disabilities',
      'Maltese',
      'Marketing',
      'Pure Maths',
      'Mathematics',
      'Maths',
      'Philosophy',
      'Physical Education',
      'Physics',
      'Psychology',
      'Religion',
      'Russian',
      'Social Studies',
      'Sociology',
      'Spanish',
      'Systems of Knowledge',
      'Artificial Intelligence',
      'Computer Science',
      'Mechanical Engineering',
      'Electrical Engineering',
      'Software Development',
      'Business Intelligence',
      'Entrepreneurship'
    ];
  }
}