class Locality{

  List<String> getLocalities(){
    return [
      'Attard',
      'Balzan',
      'Birgu',
      'Birkirkara',
      'Birzebbugia',
      'Bormla',
      'Dingli',
      'Fgura',
      'Floriana',
      'Fontana',
      'Ghajnsielem',
      'Gharb',
      'Gharghur',
      'Ghasri',
      'Ghaxaq',
      'Gudja',
      'Gzira',
      'Hamrun',
      'Iklin',
      'Isla',
      'Kalkara',
      'Kercem',
      'Kirkop',
      'Lija',
      'Luqa',
      'Marsa',
      'Marsascala',
      'Marsaxlokk',
      'Mdina',
      'Mellieha',
      'Mgarr',
      'Mosta',
      'Mqabba',
      'Msida',
      'Mtarfa',
      'Munxar',
      'Nadur',
      'Naxxar',
      'Paola',
      'Pembroke',
      'Pietà',
      'Qala',
      'Qormi',
      'Qrendi',
      'Rabat (Gozo)',
      'Rabat (Malta)',
      'Safi',
      'San Giljan',
      'San Gwann',
      'San Lawrenz',
      'Sannat',
      'San Pawl il-Bahar',
      'Santa Lucija',
      'Santa Venera',
      'Siggiewi',
      'Sliema',
      'Swieqi',
      'Tarxien',
      'Ta\' Xbiex',
      'Valletta',
      'Xaghra',
      'Xewkija',
      'Xghajra',
      'Zabbar',
      'Zebbug (Gozo)',
      'Zebbug (Malta)',
      'Zejtun',
      'Zurrieq',
    ];
  }
}